/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardBox: typeof import('./src/components/CardBox.vue')['default']
    CommentForm: typeof import('./src/components/comments/CommentForm.vue')['default']
    CommentList: typeof import('./src/components/comments/CommentList.vue')['default']
    DanmakuWall: typeof import('./src/components/DanmakuWall.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeadBar: typeof import('./src/components/HeadBar.vue')['default']
    MBTIAnalysis: typeof import('./src/components/about/MBTIAnalysis.vue')['default']
    ProfileIntro: typeof import('./src/components/about/ProfileIntro.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeDark: typeof import('./src/components/ThemeDark.vue')['default']
    WelcomeBanner: typeof import('./src/components/WelcomeBanner.vue')['default']
    YearlyGoals: typeof import('./src/components/about/YearlyGoals.vue')['default']
  }
}
